spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb
    username: username
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#  logging.level.org.springframework=WARN
#  logging.level.com.spring.ibatis.UserMapper=DEBUG
#  logging.file=logs/spring-boot-logging.log
logging:
  level:
    org.springframework: WARN
    com.suntech.project.mapper.UserMapper: DEBUG
